name: Build and push docker images

on:
  push:
    branches:
      - '*'

# Set env variables
env:
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  REPO_NAME: maxima

jobs:
  build-and-push:
    name: Build and push Maxima image
    strategy:
      fail-fast: false
      matrix:
        image_version: ['alpine', 'debian', 'alpine-latex']
        os: ['ubuntu-22.04']
    runs-on: ${{ matrix.os }}
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the commit triggering this job
        uses: actions/checkout@v4

      - name: Export Cache tokens using the Github runner shell
        uses: actions/github-script@v6
        with:
          script: |-
            core.exportVariable("ACTIONS_RUNTIME_TOKEN", process.env["ACTIONS_RUNTIME_TOKEN"])
            core.exportVariable("ACTIONS_RUNTIME_URL", process.env["ACTIONS_RUNTIME_URL"])

      # https://github.com/docker/login-action
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build image for ${{matrix.image_version}}, tagging with git SHA and latest
        id: build_image
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain
        run: |
          docker build \
          -f Dockerfile.${{matrix.image_version}} \
          -t ${DOCKERHUB_USERNAME}/${REPO_NAME}:${{matrix.image_version}}-${GITHUB_SHA} \
          -t ${DOCKERHUB_USERNAME}/${REPO_NAME}:${{matrix.image_version}}-latest \
          -t ${DOCKERHUB_USERNAME}/${REPO_NAME}:${{matrix.image_version}} \
          --cache-from=type=gha \
          --cache-to=type=gha,mode=max \
          .

      - name: Push tagged images to docker
        if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request') && github.ref_protected }}
        run: |
          docker push --all-tags $DOCKERHUB_USERNAME/$REPO_NAME
